### ISSUE TITLE
What does this term OPTION_KEY OPTION_VAL mean?

### ISSUE THREAD

**Issue by longmalongma** [lyxok1/STM-Training#7]
python3 train.py --cfg config.yaml OPTION_KEY OPTION_VAL

What does this term OPTION_KEY OPTION_VAL mean?

**Comment by lyxok1** [comment]
It is the property of yacs package that you can configure the parameters in config.yaml in the command line with key-val pairs

**Comment by longmalongma** [comment]
> It is the property of yacs package that you can configure the parameters in config.yaml in the command line with key-val pairs
Thanks for your reply.
Can this parameter be omitted?Is it okay to execute only this command？

python3 train.py --cfg config.yaml

**Comment by lyxok1** [comment]
Yes, the command line configuration is only optional

**Comment by longmalongma** [comment]
> Yes, the command line configuration is only optional
Will not selecting this parameter affect the segmentation accuracy? By the way, how do you perform quantitative tests to generate specific ones? You don’t seem to publish the code for quantitative testing?
![image](https://user-images.githubusercontent.com/40291722/113679493-670ba300-96f2-11eb-9c96-6a6cf46ed189.png)

**Comment by lyxok1** [comment]
For DAVIS, please use the official evaluation code from [here](https://github.com/fperazzi/davis-2017), for Youtube-VOS, please upload the results to the official colab [website](https://competitions.codalab.org/competitions/19544)

**Comment by longmalongma** [comment]
> For DAVIS, please use the official evaluation code from [here](https://github.com/fperazzi/davis-2017), for Youtube-VOS, please upload the results to the official colab [website](https://competitions.codalab.org/competitions/19544)

Ok,thanks!

**Comment by longmalongma** [comment]
> For DAVIS, please use the official evaluation code from [here](https://github.com/fperazzi/davis-2017), for Youtube-VOS, please upload the results to the official colab [website](https://competitions.codalab.org/competitions/19544)

Can you provide the test code?
