### ISSUE TITLE
Stuck during training

### ISSUE THREAD

**Issue by longmalongma** [lyxok1/STM-Training#8]
![image](https://user-images.githubusercontent.com/40291722/113687590-1482b480-96fb-11eb-8141-57e70e975369.png)

The network training has been stuck since 28/30. It has been stuck here all the time. Do you know why?

**Comment by longmalongma** [comment]
> ![image](https://user-images.githubusercontent.com/40291722/113687590-1482b480-96fb-11eb-8141-57e70e975369.png)
> 
> The network training has been stuck since 28/30. It has been stuck here all the time. Do you know why?

I got it

**Comment by mai556** [comment]
Hello, bro. I face the same problem. How do you solve it?
